### ISSUE TITLE
Extension stopped working yesterday

### ISSUE THREAD

**Issue by leigel3** [MengeTM/YouTube-Layout#2]
This extension stopped working yesterday. YouTube shows the new layout. I reinstalled Firefox and tried all four versions available from the Firefox extension page, with no luck. I'm just checking that this is a shared experience and not just me.

**Comment by MengeTM** [comment]
I am very sorry to hear that. I did update the extension yesterday to work with the new version YouTube rolled out to me. Since they do roll out different version to different people and regions of the world, it is very difficult for me to repair this as a one team developer.

I will still try my best to fix this. For that, I would need more information, like the add-on version, screen size, if it is on Chrome or Firefox, a very detailed description of what is not working, and how it should be working, best would be a screenshot. Please remove any personal information if you choose to upload a screenshot here by croping it and painting over sensitive areas.

However, if YouTube shows me a different version to you and if I am not able to recreate the bug, it would be almost impossible to fix it. Then we would need someone with developer skills to join this repository who is able to recreate the bug.

I am very sorry for your inconvenience and will try to solve it the best I can.
